// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'categoryIcon': string;
  'clickableMod': string;
  'energyElement': string;
  'header': string;
  'itemPickerSearch': string;
  'modList': string;
  'notUnlocked': string;
  'ornamentPreview': string;
  'selected': string;
  'socketDetailsSheet': string;
}
export const cssExports: CssExports;
export default cssExports;
